
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"

  - name: my_second_dbt_model
    description: "A starter dbt model"

  - name: communes
    description: "Merge communes data"