version: '3.9'

services:
  db:
    build: .
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgduckdb_data:/var/lib/postgresql/data
    restart: always

volumes:
  pgduckdb_data:
