# Ce fichier de docker compose est basé sur la documentation de l'image officiel de postgres : https://hub.docker.com/_/postgres/
#
# Différences :
# - Utiliser l'image postgis à la place de postgres: https://github.com/postgis/docker-postgis
# - Exposer le port de la bdd
# - Préciser un mount de volume
# - Utiliser les variables d'environnement pour les paramètres de connexion
version: '3.9'

services:

  db:
    image: postgis/postgis:16-3.5-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "/opt/make-open-data-db/${POSTGRES_DB}/mount:/var/lib/postgresql/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

